# Personal repository: https://github.com/lszsrd/B-DOP-200_Mirroring
# Destination repository: git@github.com:EpitechPromo2028/B-DOP-200-NCY-2-1-chocolatine-laszlo.serdet.git

name: chocolatine

# Sets environ variable HERE
# TODO: check permissions

on:
    push:
      branches-ignore: [ ga-ignore-* ]
    pull_request:
      branches-ignore: [ ga-ignore-* ]

jobs:
    # Checks for coding-style errors.
    check_coding_style:
        runs-on: ubuntu:latest
        container: ghcr.io/epitech/coding-style-checker:latest

        steps:
            - name: Runs coding-style report
              run: |
                check.sh . .
                if [ -z coding-style-reports.log ]; then
                    exit 1
                fi
              shell: bash

    # Checks that project actually compiles
    check_program_compilation:
        runs-on: epitechcontent/epitest-docker
        needs: check_coding_style

        steps:
            - name: Builds project
              run: |
                make && make re && make clean && make re
                if [ $? -ne 0 ]; then
                    exit 1
                fi

    # Launches unit tests
    run_tests:
        runs-on: epitechcontent/epitest-docker
        needs: check_program_compilation

        steps:
          - name: Running unit tests
            run: |
              make tests_run

    # Redirects to Epitech's repository.
    push_to_mirror:
      needs: run_tests
      runs-on: epitechcontent/epitest-docker

      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: pixta-dev/repository-mirroring-action@v1
          with:
            ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
            target_repo_url: ${{ env.MIRROR_URL }}
