# Personal repository: https://github.com/lszsrd/B-DOP-200_Mirroring
# Destination repository: git@github.com:EpitechPromo2028/B-DOP-200-NCY-2-1-chocolatine-laszlo.serdet.git

name: chocolatine
run-name: Running ${{ github.action }} workflow - ${{ github.actor }}

on:
    push:
    pull_request:
      branches-ignore:
        - 'ga-ignore-'
    
jobs:
    # Checks for coding-style errors.
    check_coding_style:
        runs-on: ghcr.io/epitech/coding-style-checker:latest
        steps:
            - uses: actions/checkout@v3
            - name: Running coding-style report
              run: |
                coding-style . .
                if [ -z coding-style-reports.log ]; then
                    exit(1)
                fi
              shell: bash